### ISSUE TITLE
Solution to the bit manipulation problem 'Non-Repeating-Numbers'

### ISSUE THREAD

**Issue by Swayam221** [Sushreesatarupa/DSA-cpp-Hacktoberfest2021#22]
I would like to provide a solution to the [finding-the-numbers](https://practice.geeksforgeeks.org/problems/finding-the-numbers0215/1) using bit manipulation.

Requesting to be assigned to this issue under the 'hacktoberfest2021' label. Thanks.

**Comment by navjotdadwal** [comment]
sir can you please assign this issue to me i am current rated 5 star at codechef with rating of 2153 and rated expert at codeforces with rating of 1776 and i use cpp language for competitive programming and can resolve this issue
