### ISSUE TITLE
Solution to the problem 'Remove Loop In Linked List'

### ISSUE THREAD

**Issue by Swayam221** [Sushreesatarupa/DSA-cpp-Hacktoberfest2021#23]
I would like to contribute by providing a solution to the [remove-loop-in-linked-list](https://practice.geeksforgeeks.org/problems/remove-loop-in-linked-list/1) problem.

Requesting to be assigned to this issue under the 'hacktoberfest2021' label. Thanks.

**Comment by Prajakta102** [comment]
I would like to add solution to the remove-loop-in-linked-list problem.

Requesting to be assigned to this issue under the 'hacktoberfest2021' label. Thanks.

**Comment by navjotdadwal** [comment]
sir can you please assign this issue to me i am current rated 5 star at codechef with rating of 2153 and rated expert at codeforces with rating of 1776 and i use cpp language for competitive programming and can resolve this issue
following are my accounts:
https://codeforces.com/profile/navjotdadwal
https://www.codechef.com/users/navjot1234
