### ISSUE TITLE
Solution to the 'Intersection Point In Y Shaped Linked List' Problem

### ISSUE THREAD

**Issue by Swayam221** [Sushreesatarupa/DSA-cpp-Hacktoberfest2021#24]
I would like to contribute by providing a solution to the [intersection-point-in-y-shaped-linked-list](https://practice.geeksforgeeks.org/problems/intersection-point-in-y-shapped-linked-lists/1) problem.

Requesting to be assigned to this issue under the 'hacktoberfest2021' label. Thanks.

**Comment by Prajakta102** [comment]
I would like to add a solution to the intersection-point-in-y-shaped-linked-list problem.

Requesting to be assigned to this issue under the 'hacktoberfest2021' label. Thanks.

**Comment by navjotdadwal** [comment]
sir can you please assign this issue to me i am current rated 5 star at codechef with rating of 2153 and rated expert at codeforces with rating of 1776 and i use cpp language for competitive programming and can resolve this issue
