### ISSUE TITLE
Solution to Floyd's cycle problem 

### ISSUE THREAD

**Issue by gayatri517** [Sushreesatarupa/DSA-cpp-Hacktoberfest2021#34]
I would like to add the code to Floyd's cycle problem in C++ in the linkedlist folder for Hacktoberfest 2021. Kindly accept my pull request.

**Comment by navjotdadwal** [comment]
sir can you please assign this issue to me i am current rated 5 star at codechef with rating of 2153 and rated expert at codeforces with rating of 1776 and i use cpp language for competitive programming and can resolve this issue

**Comment by Sushreesatarupa** [comment]
Merged!
