### ISSUE TITLE
Solution to Key Pair (Hashing Problem 1) 

### ISSUE THREAD

**Issue by pranshukas** [Sushreesatarupa/DSA-cpp-Hacktoberfest2021#60]
## Description:

I would like to work on Problem 1 mentioned in Hashing Directory. [Key Pair](https://practice.geeksforgeeks.org/problems/key-pair5616/1#)

<hr> 

<b>Requesting to be assigned to this issue under the 'hacktoberfest2021' label. </b> Thanks.

Please Assign me this issue. I am new to open source and would like to work on this issue. I have good knowledge and experience in DSA (C++).

**Comment by Sushreesatarupa** [comment]
Merged
